### ISSUE TITLE
Need a list of rooms that would be fitting for this manor

### ISSUE THREAD

**Issue by Slatebreaker** [HazmatDrone/Nyeogmi-Manor#1]
Currently unsure what would fit Nyeogmi's and guests' personal needs.
#### Current ideas:
- [x] Dining / kitchen
- [x] Bedrooms (upstairs)
- [x] Smithy
- [x] Gaol
- [x] Library (in one of the towers?)
- [ ] Additional balconies **everywhere**

**Comment by nyeogmi** [comment]
Here's some suggested room assignments! Feel free to object to any you like.

**-1F**

1. Gaol
2. Private use bedroom. (Contains beds, a small lounge. Primarily this is a location for Nyeogmi to keep people during and immediately after feeding.)
3. New vampire bedrooms: lightless, lockable rooms for recently-converted thralls.

**0F**

1. Main Entry
2. Courtyard
3. Public study 1
4. Public bathroom 1
5. Public pantry
6. Dining entry
7. Lounge (Contains a bulletin board for thrall orders)
8. Dining
9. Kitchen/pantry
10. Public study 2
11. Smithy
12. Armory
13. Watch station

**R. Tow**: Main bedroom
**F. Tow**: Library 1

**1F**

1. Canopy
2. ? (Can this be converted to bedroom space? Perhaps consider a low-light connection from the R. Tower to the lounge.)
3. Lounge, upper level/mezzanine. (Consider a staircase connecting them?)
4. Upstairs dormitory. (Maybe see if you can jam two small bedrooms in here, a bathroom in each?)
5. Gallery

**R. Tow**: Main bedroom
**F. Tow**: Library 2

**2F**

1. Roost. (Provide unlit crawl-space, suitable for vampires. Ideally this should be accessible from the main bedroom while avoiding sunlight)

**R. Tow**: Main bedroom
**F. Tow**: Library 3

**3F**

R. Tow: Main bedroom
